services:
  - type: web
    name: edgeroute
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m flask db upgrade
      python create_default_avatar.py
    startCommand: gunicorn "run:app"
    plan: free

    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_CONFIG
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: edgeroute-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      # Appwrite configuration
      - key: USE_APPWRITE
        value: "true"
      - key: APPWRITE_ENDPOINT
        value: https://cloud.appwrite.io/v1
      - key: APPWRITE_PROJECT_ID
        sync: false
      - key: APPWRITE_API_KEY
        sync: false
      - key: APPWRITE_DATABASE_ID
        sync: false
      - key: APPWRITE_USERS_COLLECTION_ID
        value: users
      - key: APPWRITE_ROADMAPS_COLLECTION_ID
        value: roadmaps
      - key: APPWRITE_ROADMAP_NODES_COLLECTION_ID
        value: roadmap_nodes
      - key: APPWRITE_USER_PROGRESS_COLLECTION_ID
        value: user_progress
      - key: APPWRITE_COMMENTS_COLLECTION_ID
        value: comments
      - key: APPWRITE_CUSTOM_ROADMAPS_COLLECTION_ID
        value: custom_roadmaps
      - key: APPWRITE_CUSTOM_ROADMAP_NODES_COLLECTION_ID
        value: custom_roadmap_nodes
      - key: APPWRITE_STORAGE_ID
        value: profile_pictures

databases:
  - name: edgeroute-db
    databaseName: edgeroute
    user: edgeroute
    plan: free
